name: Build and publish pre-release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Download cyclonedx-gomod
      uses: CycloneDX/gh-gomod-generate-sbom@v1
      with:
        version: v1

    - name: Build
      run: ./build.ps1
      shell: pwsh

    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Binaries
    #     path: binaries/

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          binaries/*